### ISSUE TITLE
Disable Lighting

### ISSUE THREAD

**Issue by ostpol** [moifort/homebridge-create-fan#7]
**Is your feature request related to a problem? Please describe:**
No.

**Describe the solution you'd like:**
An option to disable the lighting part of the HomeKit accessory for fans without lighting.

**Describe alternatives you've considered:**
It's already possible to seperate both functions in Home App, but this isn't as convenient as the described solution.

**Additional context:**
Thank you for building this Plugin! :)

**Comment by moifort** [comment]
I get your need, I'll see if I can help.

**Comment by moifort** [comment]
Can you test the version 0.0.61, you can add inside config `hasLight: false`  like below:
```json
"platforms": [ {
  "name": "Create Ceiling Fan",
  "devices": [
    {
        "id": "bx48",
        "key": "bla",
        "name": "Chambre",
        "hasLight": false
     },
     {
         "id": "bx49",
         "key": "bla",
         "name": "Salon",
         "hasLight": true
      }
    ],
}]
```

**Comment by ostpol** [comment]
Tested it, still lighting and fan.
```
        {
            "name": "Deckenventilator",
            "devices": [
                {
                    "id": "bf8318237c79eac6e0j4sh",
                    "key": "SG[t@*!PPA9a!Sgd",
                    "name": "Deckenventilator",
                    "hasLight": false
                }
            ],
            "platform": "HomebridgeCreateCeilingFan"
        }
```
![IMG_507114980428-1](https://github.com/moifort/homebridge-create-fan/assets/3061405/2a38ddcf-52d1-4c15-9777-dd604f388595)

**Comment by moifort** [comment]
Test with v0.0.63, don't forget to remove your accessories from cache `/settings/Cache Accessories`

**Comment by ostpol** [comment]
That solved it. Thanks for the fast implementation!
