### ISSUE TITLE
Connect WindCalm to Tuya & get local_key

### ISSUE THREAD

**Issue by pandizajner** [moifort/homebridge-create-fan#8]
**Describe Your Problem:**
I'm having a hard time trying to connect WindCalm to Tuya app (in order to make it visible in iot.Tuya and get the local_key)

I have connected the fan to CREATE app, but I have no idea how I should reconnect it to Tuya now. I keep holding "1h" or "1h" and "2h" buttons on the remote controller, but it doesn't seem to be working as Reset. Also I was checking the Discovery feature in  Tuya Smart app, but without any success.

**Comment by moifort** [comment]
Hello,

I think you try to follow the instructions [here](https://github.com/jasonacox/tinytuya/tree/master#setup-wizard---getting-local-keys) ? right?

Normally after create your iot.Tuya you need to sync with `Smart Life` app. 

I am not sure if I can help, but don't hesitate if you have any question?

**Comment by pandizajner** [comment]
Thank you! I eventually managed to run "paring mode" in the device and it has shown up in the Tuya Smart app. Also in IOT Tuya.
